"""empty message

Revision ID: 73eae43a76fe
Revises: e5ea028f0945
Create Date: 2025-05-15 12:57:26.426126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73eae43a76fe'
down_revision = 'e5ea028f0945'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
